const WORD_PACKS = {
  "🍎 Food": [
    { real: "Pizza", impostor: "Slice" },
    { real: "Burger", impostor: "Bun" },
    { real: "Hot Dog", impostor: "Long" },
    { real: "Ice Cream", impostor: "Freezing" },
    { real: "Pancakes", impostor: "Breakfast" },
    { real: "Popcorn", impostor: "Basket" },
    { real: "Birthday Cake", impostor: "Fire" },
    { real: "Cake", impostor: "Birthday" },
    { real: "Spaghetti", impostor: "Fork" },
    { real: "Taco", impostor: "Fold" },
    { real: "Donut", impostor: "Round" },
    { real: "Sandwich", impostor: "Lunch" },
    { real: "Sausage Roll", impostor: "Cylinder" },
    { real: "Meal Deal", impostor: "Combo" },
    { real: "Toast", impostor: "Butter" },
    { real: "Mashed Potatoes", impostor: "Gravy" },
    { real: "Cereal", impostor: "Spoon" },
    { real: "Scrambled Eggs", impostor: "Breakfast" },
    { real: "Milkshake", impostor: "Straw" },
    { real: "Pepsi", impostor: "Bubbly" },
    { real: "Sparkling Water", impostor: "Bubbly" },
    { real: "Smoothie", impostor: "Blend" },
    { real: "Watermelon", impostor: "Round" },
    { real: "Banana Split", impostor: "Sundae" },
    { real: "Chocolate Bar", impostor: "Wrapper" },
    { real: "Candy Cane", impostor: "Stick" },
    { real: "Lollipop", impostor: "Stick" },
    { real: "Pretzel", impostor: "Twist" },
    { real: "Cheesecake", impostor: "Sweet" },
    { real: "Mozzarella Sticks", impostor: "String" },
    { real: "Porridge", impostor: "Oat" },
    { real: "Pickles", impostor: "Jar" },
    { real: "Garlic Bread", impostor: "Butter" },
    { real: "Ramen", impostor: "Steam" },
    { real: "Omelette", impostor: "Fold" },
    { real: "Fish and Chips", impostor: "Ocean" },
    { real: "Full English", impostor: "Breakfast" },
    { real: "Yorkshire Pudding", impostor: "Location" },
    { real: "Jaffa Cakes", impostor: "Debate" },
    { real: "Baked Beans", impostor: "Toast" },
    { real: "Crumpets", impostor: "Round" },
    { real: "Tea and Biscuits", impostor: "Break" },
    { real: "Cornish Pasty", impostor: "Fold" },
    { real: "Welsh Rarebit", impostor: "Fold" },
    { real: "Custard", impostor: "Yellow" },
    { real: "Bara Brith", impostor: "Fruit" },
    { real: "Coffee", impostor: "Cup" },
    { real: "Hot Chocolate", impostor: "Cozy" },
    { real: "Wrap", impostor: "Fold" },
    { real: "Scotch Egg", impostor: "Picnic" },
    { real: "Water Bottle", impostor: "Cold" },
    { real: "Orange Juice", impostor: "Carton" },
    { real: "Milk", impostor: "Carton" },
    { real: "Squash", impostor: "Dilute" },
    { real: "Lemonade", impostor: "Stand" },
    { real: "Spring Roll", impostor: "Crunch" },
    { real: "Onion Rings", impostor: "Round" },
    { real: "Donner Kebab", impostor: "Late" },
    { real: "Fish", impostor: "Batter" },
    { real: "Chips", impostor: "Salt" },
    { real: "Waffles", impostor: "Debate" },
  ],
  "🌍 Pop Culture": [
    { real: "I'm sure I've just seen Tin Man walk past window", impostor: "Metal" },
    { real: "Guess who's jealous of Adele? BEYONCÉ!", impostor: "Envy" },
    { real: "Mama, a girl behind you", impostor: "Purple Heart" },
    { real: "Donatella VERSACE 💜", impostor: "Purple Heart" },
    { real: "Please can I go to Ellie and mason House", impostor: "Purple Heart" },
    { real: "Fish Girl", impostor: "Ocean" },
    { real: "Empty Chair, do a solo!", impostor: "Dance" },
  ]
};

let enabledPacks = Object.keys(WORD_PACKS);
