const WORD_PACKS = {
  "🍎 Foods & Drinks": [
    { real: "Pizza", impostor: "Slice" },
    { real: "Burger", impostor: "Bun" },
    { real: "Hot Dog", impostor: "Long" },
    { real: "Ice Cream", impostor: "Freezing" },
    { real: "Pancakes", impostor: "Breakfast" },
    { real: "Popcorn", impostor: "Basket" },
    { real: "Birthday Cake", impostor: "Fire" },
    { real: "Cake", impostor: "Birthday" },
    { real: "Spaghetti", impostor: "Fork" },
    { real: "Taco", impostor: "Fold" },
    { real: "Donut", impostor: "Round" },
    { real: "Sandwich", impostor: "Lunch" },
    { real: "Sausage Roll", impostor: "Cylinder" },
    { real: "Meal Deal", impostor: "Combo" },
    { real: "Toast", impostor: "Butter" },
    { real: "Mashed Potatoes", impostor: "Gravy" },
    { real: "Cereal", impostor: "Spoon" },
    { real: "Scrambled Eggs", impostor: "Breakfast" },
    { real: "Milkshake", impostor: "Straw" },
    { real: "Pepsi", impostor: "Bubbly" },
    { real: "Sparkling Water", impostor: "Bubbly" },
    { real: "Smoothie", impostor: "Blend" },
    { real: "Watermelon", impostor: "Round" },
    { real: "Banana Split", impostor: "Sundae" },
    { real: "Chocolate Bar", impostor: "Wrapper" },
    { real: "Candy Cane", impostor: "Stick" },
    { real: "Lollipop", impostor: "Stick" },
    { real: "Pretzel", impostor: "Twist" },
    { real: "Cheesecake", impostor: "Sweet" },
    { real: "Mozzarella Sticks", impostor: "String" },
    { real: "Porridge", impostor: "Oat" },
    { real: "Pickles", impostor: "Jar" },
    { real: "Garlic Bread", impostor: "Butter" },
    { real: "Ramen", impostor: "Steam" },
    { real: "Omelette", impostor: "Fold" },
    { real: "Fish and Chips", impostor: "Ocean" },
    { real: "Full English", impostor: "Breakfast" },
    { real: "Yorkshire Pudding", impostor: "Location" },
    { real: "Jaffa Cakes", impostor: "Debate" },
    { real: "Baked Beans", impostor: "Toast" },
    { real: "Crumpets", impostor: "Round" },
    { real: "Tea and Biscuits", impostor: "Break" },
    { real: "Cornish Pasty", impostor: "Fold" },
    { real: "Welsh Rarebit", impostor: "Fold" },
    { real: "Custard", impostor: "Yellow" },
    { real: "Bara Brith", impostor: "Fruit" },
    { real: "Coffee", impostor: "Cup" },
    { real: "Hot Chocolate", impostor: "Cozy" },
    { real: "Wrap", impostor: "Fold" },
    { real: "Scotch Egg", impostor: "Picnic" },
    { real: "Water Bottle", impostor: "Cold" },
    { real: "Orange Juice", impostor: "Carton" },
    { real: "Milk", impostor: "Carton" },
    { real: "Squash", impostor: "Dilute" },
    { real: "Lemonade", impostor: "Stand" },
    { real: "Spring Roll", impostor: "Crunch" },
    { real: "Onion Rings", impostor: "Round" },
    { real: "Donner Kebab", impostor: "Late" },
    { real: "Fish", impostor: "Batter" },
    { real: "Chips", impostor: "Salt" },
    { real: "Waffles", impostor: "Debate" },
    { real: "Pringles", impostor: "Crunch" },
  ],
  "🧠 Everyday Objects": [
  { real: "Phone", impostor: "Screen" },
  { real: "Laptop", impostor: "Keys" },
  { real: "Tablet", impostor: "Touch" },
  { real: "Headphones", impostor: "Sound" },
  { real: "Charger", impostor: "Plug" },
  { real: "Remote Control", impostor: "Click" },
  { real: "Television", impostor: "Glass" },
  { real: "Camera", impostor: "Lens" },
  { real: "Speaker", impostor: "Loud" },
  { real: "Smartwatch", impostor: "Wrist" },
  { real: "Sofa", impostor: "Sit" },
  { real: "Chair", impostor: "Legs" },
  { real: "Table", impostor: "Surface" },
  { real: "Bed", impostor: "Sleep" },
  { real: "Pillow", impostor: "Soft" },
  { real: "Blanket", impostor: "Warm" },
  { real: "Lamp", impostor: "Light" },
  { real: "Curtains", impostor: "Pull" },
  { real: "Carpet", impostor: "Floor" },
  { real: "Window", impostor: "View" },
  { real: "Doorknob", impostor: "Turn" },
  { real: "Door Handle", impostor: "Pull" },
  { real: "Light Switch", impostor: "Flick" },
  { real: "Doorbell", impostor: "Ring" },
  { real: "Mailbox", impostor: "Post" },
  { real: "Toothbrush", impostor: "Bristles" },
  { real: "Toothpaste", impostor: "Squeeze" },
  { real: "Shampoo", impostor: "Bottle" },
  { real: "Soap", impostor: "Foam" },
  { real: "Towel", impostor: "Dry" },
  { real: "Razor", impostor: "Blade" },
  { real: "Shower", impostor: "Steam" },
  { real: "Sink", impostor: "Drain" },
  { real: "Toilet Paper", impostor: "Roll" },
  { real: "Hairbrush", impostor: "Tangle" },
  { real: "Backpack", impostor: "Carry" },
  { real: "Wallet", impostor: "Cards" },
  { real: "Umbrella", impostor: "Rain" },
  { real: "Book", impostor: "Pages" },
  { real: "Notebook", impostor: "Lines" },
  { real: "Pen", impostor: "Ink" },
  { real: "Pencil", impostor: "Wood" },
  { real: "Scissors", impostor: "Cut" },
  { real: "Tape", impostor: "Stick" },
  { real: "Clock", impostor: "Time" },
  { real: "Alarm Clock", impostor: "Wake" },
  { real: "Calendar", impostor: "Days" },
  { real: "Watch", impostor: "Wrist" },
  { real: "Phone Case", impostor: "Protect" },
  { real: "SIM Card", impostor: "Signal" },
  { real: "USB Stick", impostor: "Storage" },
  { real: "Extension Lead", impostor: "Sockets" },
  { real: "Power Bank", impostor: "Charge" },
  { real: "Earbuds Case", impostor: "Pods" },
  { real: "Notebook Paper", impostor: "Write" },
  { real: "Highlighter", impostor: "Glow" },
  { real: "Eraser", impostor: "Rub" },
  { real: "Glue Stick", impostor: "Stick" },
  { real: "Ruler", impostor: "Measure" },
  { real: "Compass", impostor: "Circle" },
  { real: "Calculator", impostor: "Numbers" },
  { real: "Staples", impostor: "Bind" },
  { real: "Folder", impostor: "Organise" },
  { real: "Clipboard", impostor: "Hold" },
  { real: "Bin", impostor: "Trash" },
  { real: "Dustpan", impostor: "Sweep" },
  { real: "Broom", impostor: "Sweep" },
  { real: "Vacuum", impostor: "Suck" },
  { real: "Mop", impostor: "Wet" },
  { real: "Bucket", impostor: "Carry" },
  { real: "Sponge", impostor: "Soak" },
  { real: "Washing Basket", impostor: "Laundry" },
  { real: "Clothes Peg", impostor: "Clip" },
  { real: "Iron", impostor: "Press" },
  { real: "Plate", impostor: "Round" },
  { real: "Bowl", impostor: "Deep" },
  { real: "Cup", impostor: "Sip" },
  { real: "Mug", impostor: "Hot" },
  { real: "Fork", impostor: "Prongs" },
  { real: "Knife", impostor: "Sharp" },
  { real: "Spoon", impostor: "Scoop" },
  { real: "Bottle", impostor: "Cap" },
  { real: "Jar", impostor: "Twist" },
  { real: "Can", impostor: "Pop" },
  { real: "Button", impostor: "Press" },
  { real: "Plug", impostor: "Socket" },
  { real: "Cable", impostor: "Wire" },
  { real: "Battery", impostor: "Power" },
  { real: "Light Bulb", impostor: "Glow" },
  { real: "Coin", impostor: "Metal" },
  { real: "Paperclip", impostor: "Bend" },
  { real: "Stapler", impostor: "Pinch" },
  { real: "Zipper", impostor: "Pull" },
  { real: "Rubber Band", impostor: "Stretch" }
],
  "™️ Brands": [
    { real: "Tesco", impostor: "Meal Deal" },
    { real: "Sainsbury's", impostor: "Meal Deal" },
    { real: "Asda", impostor: "Green" },
    { real: "Aldi", impostor: "Twins" },
    { real: "Lidl", impostor: "Twins" },
    { real: "Co-Op", impostor: "Flood" },
    { real: "Waitrose", impostor: "Green" },
    { real: "M&S", impostor: "Name" },
    { real: "Iceland", impostor: "Frozen" },
    { real: "Morrisons", impostor: "Fresh" },
    { real: "McDonald's", impostor: "Golden" },
    { real: "Burger King", impostor: "Flame" },
    { real: "KFC", impostor: "Bucket" },
    { real: "Domino's", impostor: "Effect" },
    { real: "Greggs", impostor: "Bakery" },
    { real: "Subway", impostor: "Feet" },
    { real: "Costa Coffee", impostor: "Cup" },
    { real: "Starbucks", impostor: "Mermaid" },
    { real: "Nike", impostor: "Motivate" },
    { real: "Adidas", impostor: "Stripes" },
    { real: "Next", impostor: "Catalog" },
    { real: "Primark", impostor: "Cheap" },
    { real: "Apple", impostor: "Bite" },
    { real: "Samsung", impostor: "Galaxy" },
    { real: "Google", impostor: "Search" },
    { real: "Amazon", impostor: "Box" },
    { real: "Lynx", impostor: "Scent" },
    { real: "Bath & Body Works", impostor: "Scent" },
    { real: "JD Sports", impostor: "Trainers" },
    { real: "Walkers", impostor: "Crunch" },
    { real: "Pringles", impostor: "Crunch" },
  ],

  "🌍 Pop Culture": [
    { real: "I'm sure I've just seen Tin Man walk past window", impostor: "Metal" },
    { real: "Guess who's jealous of Adele? BEYONCÉ!", impostor: "Envy" },
    { real: "Mama, a girl behind you", impostor: "Purple Heart" },
    { real: "Donatella VERSACE 💜", impostor: "Purple Heart" },
    { real: "Please can I go to Ellie and mason House", impostor: "Purple Heart" },
    { real: "Fish Girl", impostor: "Ocean" },
    { real: "Empty Chair, do a solo!", impostor: "Dance" },
    { real: "That was a fail, I hate myself, Catch me knuckles.", impostor: "Cooking" },
    { real: "Look straight into the webcam and say 'Dua Lipa is the greatest popstar in history'", impostor: "Technology" },
    { real: "If you kick every latino out of this country, then who is going to be cleaning your toilet, Donald Trump?", impostor: "Embarrassing" },
    { real: "I think we all sing", impostor: "Envy" },
    { real: "Cinderella, because she worked for what she got. She wasn't some little hoe mermaid", impostor: "Princess" },
    { real: "With liberty and justice for all", impostor: "Fall" },
    { real: "You just mad cuz your son fav color is 5..", impostor: "Argument" },
    { real: "I can't live without my KKW contour", impostor: "Kardashian" },
    { real: "Kim Kardashian's diamond earring", impostor: "Kardashian" },
    { real: "It's not okay though, It's not! You know, on Roblox!", impostor: "Kardashian" },
    { real: "I've seen skid marks better than James Charles' contour", impostor: "Makeup" },
    { real: "James Charles running and faceplanting in the middle of a mall", impostor: "Fall" },
    { real: "Was the 95 not enough for you?", impostor: "Popularity" },
    { real: "bacon bacon bacon", impostor: "Technology" },
    { real: "I mean, let me ask the audience.", impostor: "Technology" },
    { real: "The journey is usually the part that you remember anyways", impostor: "Cough" },
    { real: "Do you wear wigs? Have you worn wigs? Will you wear wigs? When will you wear wigs?", impostor: "Costume" },
    { real: "Damn, double homicide", impostor: "Twins" },
    { real: "Yes!", impostor: "Excitement" },
    { real: "Do you think people who hate Osama Bin Laden are jealous of him?", impostor: "Envy" },
    { real: "I finna be in the pit", impostor: "Concert" },
    { real: "Ellie Goulding Glitching", impostor: "Concert" },
    { real: "You may say I'm a dreamer", impostor: "Concert" },
    { real: "Toxic Gossip Train", impostor: "Persian Cats" },
    { real: "Hyperpigmentation", impostor: "Senior Photos" },
    { real: "Well, you should probably eat", impostor: "Interview" },
    { real: "Divorce babes, divorce", impostor: "Live" },
    { real: "What would you do if when you okay so he said yes would go? I don't know what you mean there babes.", impostor: "Live" },
    { real: "My favourite dish? I like mugs.", impostor: "Dish" },
    { real: "Ant & Seb's Mysterious Girl X Factor Audition", impostor: "Mystery" },
    { real: "It scares me to be still, it's terrifying, yeah.", impostor: "Standing" },
    { real: "Can you say... magnetic? Charismatic..? Solid gold and shocking pink.", impostor: "Teleprompter" },
    { real: "Deedee Megadoodoo", impostor: "News" },
    { real: "I'm gay........ Actually, I'm not.", impostor: "Pink" },
    { real: "I have the one and only 24K gold labubu", impostor: "Exclusive" },
    { real: "It's not clocking to you that I'm standing on business", impostor: "Business" },
    { real: "The dirtier the bettah!", impostor: "Carrot" },
  ]
};

let enabledPacks = Object.keys(WORD_PACKS);
